spring:
  application:
    name: nintendo-server

  profiles:
    active: dev

  data:
    mongodb:
      nintendo:
        uri: ${nintendo.mongodb.url}

    redis:
      # Redis服务器地址
      host: ${nintendo.redis.host}
      # Redis服务器端口号
      port: ${nintendo.redis.port}
      # 使用的数据库索引，默认是0
      database: 0
      # 连接超时时间
      timeout: 1800000
      # 设置密码
      password: ${nintendo.redis.password}
      lettuce:
        pool:
          # 最大阻塞等待时间，负数表示没有限制
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 5
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中最大连接数，负数表示没有限制
          max-active: 20
      repositories:
        enabled: false

  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG

telegram:
  name: ${nintendo.telegram.name}
  token: ${nintendo.telegram.token}

wx:
  mp:
    callback: ${nintendo.wx.callback}
    configs:
      - appId: ${nintendo.wx.appId} # 第一个公众号的appid
        secret: ${nintendo.wx.secret} # 公众号的appsecret
        token: ${nintendo.wx.token} # 接口配置里的Token值
        aesKey: ${nintendo.wx.aesKey} # 接口配置里的EncodingAESKey值

server:
  port: ${nintendo.server.port}

chat:
  chatgpt:
    enable: ${nintendo.chatgpt.enable}
    AIUserId: ${nintendo.chatgpt.uid}
    key: ${nintendo.chatgpt.key}
    proxyUrl: ${nintendo.chatgpt.proxyUrl}
  chatglm:
    enable: ${nintendo.chatglm.enable}
    url: ${nintendo.chatglm.url}
    minute: 3 # 每个用户每3分钟可以请求一次
    AIUserId: ${nintendo.chatglm.uid}